const items = {
    small_aid: {
        name: 'small_aid',
        caption: 'items.small_aid.name',
        descript: 'items.small_aid.descript',
        type: 'food',
        onUse: `this.setAttr('player', 'hp', 40); this.changeInventory('player', 'small_aid', -1);`,
    },
    small_battery: {
        name: 'small_battery',
        caption: 'items.small_battery.name',
        descript: 'items.small_battery.descript',
        type: 'weapon',
        onUse: `this.setAttr('player', 'hp', 40); this.changeInventory('player', 'small_aid', -1);`,
    },

    // Weapon
    // Pistol
    instigator: {
        name: 'instigator',
        caption: 'items.weapon.instigator.name',
        descript: '5<img src="img/interface/icon-physic.png">',
        image: 'pistol-instigator',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { physic: 5 })`,
        onUnequip: `this.changeAtks('player', { physic: -5 })`,
    },
    referee: {
        name: 'referee',
        caption: 'items.weapon.referee.name',
        descript: '10<img src="img/interface/icon-physic.png">',
        image: 'pistol-referee',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { physic: 10 })`,
        onUnequip: `this.changeAtks('player', { physic: -10 })`,
    },
    marauder: {
        name: 'marauder',
        caption: 'items.weapon.marauder.name',
        descript: '15<img src="img/interface/icon-physic.png">',
        image: 'pistol-marauder',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { physic: 15 })`,
        onUnequip: `this.changeAtks('player', { physic: -15 })`,
    },
    burner: {
        name: 'burner',
        caption: 'items.weapon.burner.name',
        descript: '5<img src="img/interface/icon-temperature.png">',
        image: 'pistol-burner',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { temperature: 5 })`,
        onUnequip: `this.changeAtks('player', { temperature: -5 })`,
    },
    pride: {
        name: 'pride',
        caption: 'items.weapon.pride.name',
        descript: '10<img src="img/interface/icon-temperature.png">',
        image: 'pistol-pride',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { temperature: 10 })`,
        onUnequip: `this.changeAtks('player', { temperature: -10 })`,
    },
    goblin: {
        name: 'goblin',
        caption: 'items.weapon.goblin.name',
        descript: '15<img src="img/interface/icon-temperature.png">',
        image: 'pistol-goblin',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { temperature: 15 })`,
        onUnequip: `this.changeAtks('player', { temperature: -15 })`,
    },
    ray: {
        name: 'ray',
        caption: 'items.weapon.ray.name',
        descript: '20<img src="img/interface/icon-temperature.png">',
        image: 'pistol-ray',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { temperature: 20 })`,
        onUnequip: `this.changeAtks('player', { temperature: -20 })`,
    },
    splitter: {
        name: 'splitter',
        caption: 'items.weapon.splitter.name',
        descript: '5<img src="img/interface/icon-toxic.png"> 5<img src="img/interface/icon-radioactive.png"> 5<img src="img/interface/icon-temperature.png"> 5<img src="img/interface/icon-physic.png">',
        image: 'pistol-splitter',
        type: 'weapon',
        size: 'oneHand',
        onEquip: `this.changeAtks('player', { toxic: 5, radioactive: 5, temperature: 5, physic: 5 })`,
        onUnequip: `this.changeAtks('player', { toxic: -5, radioactive: -5, temperature: -5, physic: -5 })`,
    },
    // Rifle
    confessor: {
        name: 'confessor',
        caption: 'items.weapon.confessor.name',
        descript: '45<img src="img/interface/icon-physic.png">',
        image: 'rifle-confessor',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 45 })`,
        onUnequip: `this.changeAtks('player', { physic: 45 })`,
    },
    dominant: {
        name: 'dominant',
        caption: 'items.weapon.dominant.name',
        descript: '50<img src="img/interface/icon-physic.png">',
        image: 'rifle-dominant',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 50 })`,
        onUnequip: `this.changeAtks('player', { physic: 50 })`,
    },
    argument: {
        name: 'argument',
        caption: 'items.weapon.argument.name',
        descript: '55<img src="img/interface/icon-physic.png">',
        image: 'rifle-argument',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 55 })`,
        onUnequip: `this.changeAtks('player', { physic: 55 })`,
    },
    weevil: {
        name: 'weevil',
        caption: 'items.weapon.weevil.name',
        descript: '60<img src="img/interface/icon-physic.png">',
        image: 'rifle-weevil',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 60 })`,
        onUnequip: `this.changeAtks('player', { physic: 60 })`,
    },
    aristocrat: {
        name: 'aristocrat',
        caption: 'items.weapon.aristocrat.name',
        descript: '65<img src="img/interface/icon-physic.png">',
        image: 'rifle-aristocrat',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 65 })`,
        onUnequip: `this.changeAtks('player', { physic: 65 })`,
    },
    shark: {
        name: 'shark',
        caption: 'items.weapon.shark.name',
        descript: '70<img src="img/interface/icon-physic.png">',
        image: 'rifle-shark',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 70 })`,
        onUnequip: `this.changeAtks('player', { physic: 70 })`,
    },
    ork: {
        name: 'ork',
        caption: 'items.weapon.ork.name',
        descript: '10<img src="img/interface/icon-temperature.png"> 65<img src="img/interface/icon-physic.png">',
        image: 'rifle-ork',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { temperature: 10, physic: 65 })`,
        onUnequip: `this.changeAtks('player', { temperature: -10, physic: -65 })`,
    },
    last_argument: {
        name: 'last_argument',
        caption: 'items.weapon.last_argument.name',
        descript: '80<img src="img/interface/icon-physic.png">',
        image: 'rifle-last-argument',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { physic: 80 })`,
        onUnequip: `this.changeAtks('player', { physic: 80 })`,
    },
    rot: {
        name: 'rot',
        caption: 'items.weapon.rot.name',
        descript: '10<img src="img/interface/icon-toxic.png"> 40<img src="img/interface/icon-radioactive.png">',
        image: 'rifle-rot',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { toxic: 10, radioactive: 40 })`,
        onUnequip: `this.changeAtks('player', { toxic: -10, radioactive: -40 })`,
    },
    last_breath: {
        name: 'last_breath',
        caption: 'items.weapon.last_breath.name',
        descript: '15<img src="img/interface/icon-toxic.png"> 45<img src="img/interface/icon-radioactive.png">',
        image: 'rifle-last-breath',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { toxic: 15, radioactive: 45 })`,
        onUnequip: `this.changeAtks('player', { toxic: -15, radioactive: -45 })`,
    },
    messenger: {
        name: 'messenger',
        caption: 'items.weapon.messenger.name',
        descript: '70<img src="img/interface/icon-temperature.png">',
        image: 'rifle-messenger',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { temperature: 70 })`,
        onUnequip: `this.changeAtks('player', { temperature: -70 })`,
    },
    prejudice: {
        name: 'prejudice',
        caption: 'items.weapon.prejudice.name',
        descript: '80<img src="img/interface/icon-temperature.png">',
        image: 'rifle-prejudice',
        type: 'weapon',
        onEquip: `this.changeAtks('player', { temperature: 80 })`,
        onUnequip: `this.changeAtks('player', { temperature: -80 })`,
    },
    pulsar: {
        name: 'pulsar',
        caption: 'items.weapon.pulsar.name',
        descript: '20<img src="img/interface/icon-radioactive.png"> 70<img src="img/interface/icon-temperature.png">',
        image: 'rifle-pulsar',
        size: 'twoHand',
        type: 'weapon',
        onEquip: `this.changeAtks('player', { radioactive: 20, temperature: 70 })`,
        onUnequip: `this.changeAtks('player', { radioactive: -20, temperature: -70 })`,
    },
    gyurza: {
        name: 'gyurza',
        caption: 'items.weapon.gyurza.name',
        descript: '100<img src="img/interface/icon-toxic.png">',
        image: 'rifle-gyurza',
        size: 'twoHand',
        type: 'weapon',
        onEquip: `this.changeAtks('player', { toxic: 100 })`,
        onUnequip: `this.changeAtks('player', { toxic: -100 })`,
    },
    radscorpion: {
        name: 'radscorpion',
        caption: 'items.weapon.radscorpion.name',
        descript: '100<img src="img/interface/icon-radioctive.png">',
        image: 'rifle-radscorpion',
        size: 'twoHand',
        type: 'weapon',
        onEquip: `this.changeAtks('player', { radioactive: 100 })`,
        onUnequip: `this.changeAtks('player', { radioactive: -100 })`,
    },
    annihilator: {
        name: 'annihilator',
        caption: 'items.weapon.annihilator.name',
        descript: '25<img src="img/interface/icon-toxic.png"> 25<img src="img/interface/icon-radioactive.png"> 25<img src="img/interface/icon-temperature.png"> 25<img src="img/interface/icon-physic.png">',
        image: 'rifle-annihilator',
        type: 'weapon',
        size: 'twoHand',
        onEquip: `this.changeAtks('player', { toxic: 25, radioactive: 25, temperature: 25, physic: 25 })`,
        onUnequip: `this.changeAtks('player', { toxic: -25, radioactive: -25, temperature: -25, physic: -25 })`,
    },

    // Suits
    // Light - Special
    citizen: {
        name: 'citizen',
        caption: 'items.suit.citizen.name',
        descript: 'items.suit.citizen.descript',
        image: 'light-special-citizen',
        type: 'suit',
        onEquip: `this.changeAttrs('player', { oxygen: 10, toxic: 10, radioactive: 10, temperature: 10, physic: 5 })`,
        onUnequip: `this.changeAttrs('player', { oxygen: -10, toxic: -10, radioactive: -10, temperature: -10, physic: -5 })`,
    },
    starsky: {
        name: 'starsky',
        caption: 'items.suit.starsky.name',
        descript: 'items.suit.starsky.descript',
        image: 'light-special-starsky',
        type: 'suit',
        onEquip: `this.changeAttrs('player', { oxygen: 50, toxic: 15, radioactive: 15, temperature: 15, physic: 10 })`,
        onUnequip: `this.changeAttrs('player', { oxygen: -50, toxic: -15, radioactive: -15, temperature: -15, physic: -10 })`,
    },
    // Light - Pilot
    topgun: {
        name: 'topgun',
        caption: 'items.suit.topgun.name',
        descript: 'items.suit.topgun.descript',
        image: 'light-pilot-topgun',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    toxicgrog: {
        name: 'toxicgrog',
        caption: 'items.suit.toxicgrog.name',
        descript: 'items.suit.toxicgrog.descript',
        image: 'light-pilot-toxicgrog',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    grasshoper: {
        name: 'grasshoper',
        caption: 'items.suit.grasshoper.name',
        descript: 'items.suit.grasshoper.descript',
        image: 'light-pilot-grasshoper',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    octopus: {
        name: 'octopus',
        caption: 'items.suit.octopus.name',
        descript: 'items.suit.octopus.descript',
        image: 'light-pilot-octopus',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Light - Infantry
    butterfly: {
        name: 'butterfly',
        caption: 'items.suit.butterfly.name',
        descript: 'items.suit.butterfly.descript',
        image: 'light-infantry-butterfly',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    ironman: {
        name: 'ironman',
        caption: 'items.suit.ironman.name',
        descript: 'items.suit.ironman.descript',
        image: 'light-infantry-ironman',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    nightwolf: {
        name: 'nightwolf',
        caption: 'items.suit.nightwolf.name',
        descript: 'items.suit.nightwolf.descript',
        image: 'light-infantry-nightwolf',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Light - Science
    seekerI: {
        name: 'seekerI',
        caption: 'items.suit.seekerI.name',
        descript: 'items.suit.seekerI.descript',
        image: 'light-science-seekerI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    assistant: {
        name: 'assistant',
        caption: 'items.suit.assistant.name',
        descript: 'items.suit.assistant.descript',
        image: 'light-science-assistant',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    professor: {
        name: 'professor',
        caption: 'items.suit.professor.name',
        descript: 'items.suit.professor.descript',
        image: 'light-science-professor',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Light - Technic
    assemblerI: {
        name: 'assemblerI',
        caption: 'items.suit.assemblerI.name',
        descript: 'items.suit.assemblerI.descript',
        image: 'light-technic-assemblerI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    highvoltage: {
        name: 'highvoltage',
        caption: 'items.suit.highvoltage.name',
        descript: 'items.suit.highvoltage.descript',
        image: 'light-technic-highvoltage',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    scarab: {
        name: 'scarab',
        caption: 'items.suit.scarab.name',
        descript: 'items.suit.scarab.descript',
        image: 'light-technic-scarab',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Light - Pioneer
    consul: {
        name: 'consul',
        caption: 'items.suit.consul.name',
        descript: 'items.suit.consul.descript',
        image: 'light-pioneer-consul',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    nomad: {
        name: 'nomad',
        caption: 'items.suit.nomad.name',
        descript: 'items.suit.nomad.descript',
        image: 'light-pioneer-nomad',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    pioneerI: {
        name: 'pioneerI',
        caption: 'items.suit.pioneerI.name',
        descript: 'items.suit.pioneerI.descript',
        image: 'light-pioneer-pioneerI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    pioneerII: {
        name: 'pioneerII',
        caption: 'items.suit.pioneerII.name',
        descript: 'items.suit.pioneerII.descript',
        image: 'light-pioneer-pioneerII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    predator: {
        name: 'predator',
        caption: 'items.suit.predator.name',
        descript: 'items.suit.predator.descript',
        image: 'light-pioneer-predator',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Megium - Pilot
    deathangel: {
        name: 'deathangel',
        caption: 'items.suit.deathangel.name',
        descript: 'items.suit.deathangel.descript',
        image: 'medium-pilot-deathangel',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    grasshoperII: {
        name: 'grasshoperII',
        caption: 'items.suit.grasshoperII.name',
        descript: 'items.suit.grasshoperII.descript',
        image: 'medium-pilot-grasshoperII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Megium - Infantry
    redeagle: {
        name: 'redeagle',
        caption: 'items.suit.redeagle.name',
        descript: 'items.suit.redeagle.descript',
        image: 'medium-infantry-redeagle',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    yelloweagle: {
        name: 'yelloweagle',
        caption: 'items.suit.yelloweagle.name',
        descript: 'items.suit.yelloweagle.descript',
        image: 'medium-infantry-yelloweagle',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    blueeagle: {
        name: 'blueeagle',
        caption: 'items.suit.blueeagle.name',
        descript: 'items.suit.blueeagle.descript',
        image: 'medium-infantry-blueeagle',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Megium - Science
    seekerII: {
        name: 'seekerII',
        caption: 'items.suit.seekerII.name',
        descript: 'items.suit.seekerII.descript',
        image: 'medium-science-seekerII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Megium - Technic
    assemblerII: {
        name: 'assemblerII',
        caption: 'items.suit.assemblerII.name',
        descript: 'items.suit.assemblerII.descript',
        image: 'medium-technic-assemblerII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    bulldozer: {
        name: 'bulldozer',
        caption: 'items.suit.bulldozer.name',
        descript: 'items.suit.bulldozer.descript',
        image: 'medium-technic-bulldozer',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    diggerI: {
        name: 'diggerI',
        caption: 'items.suit.diggerI.name',
        descript: 'items.suit.diggerI.descript',
        image: 'medium-technic-diggerI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    diggerII: {
        name: 'diggerII',
        caption: 'items.suit.diggerII.name',
        descript: 'items.suit.diggerII.descript',
        image: 'medium-technic-diggerII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Megium - Pioneer
    knight: {
        name: 'knight',
        caption: 'items.suit.knight.name',
        descript: 'items.suit.knight.descript',
        image: 'medium-pioneer-knight',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Heavy - Pilot
    bigmama: {
        name: 'bigmama',
        caption: 'items.suit.bigmama.name',
        descript: 'items.suit.bigmama.descript',
        image: 'heavy-pilot-bigmama',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Heavy - Infantry
    madbuffalo: {
        name: 'madbuffalo',
        caption: 'items.suit.madbuffalo.name',
        descript: 'items.suit.madbuffalo.descript',
        image: 'heavy-infantry-madbuffalo',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Heavy - Science
    universeI: {
        name: 'universeI',
        caption: 'items.suit.universeI.name',
        descript: 'items.suit.universeI.descript',
        image: 'heavy-science-universeI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    universeII: {
        name: 'universeII',
        caption: 'items.suit.universeII.name',
        descript: 'items.suit.universeII.descript',
        image: 'heavy-science-universeII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Heavy - Technic
    createrI: {
        name: 'createrI',
        caption: 'items.suit.createrI.name',
        descript: 'items.suit.createrI.descript',
        image: 'heavy-technic-createrI',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    createrII: {
        name: 'createrII',
        caption: 'items.suit.createrII.name',
        descript: 'items.suit.createrII.descript',
        image: 'heavy-technic-createrII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
    diggerIII: {
        name: 'diggerIII',
        caption: 'items.suit.diggerIII.name',
        descript: 'items.suit.diggerIII.descript',
        image: 'heavy-technic-diggerIII',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },

    // Heavy - Pioneer
    immortal: {
        name: 'immortal',
        caption: 'items.suit.immortal.name',
        descript: 'items.suit.immortal.descript',
        image: 'heavy-pioneer-immortal',
        type: 'suit',
        onEquip: `this.changeAtks('player', {})`,
        onUnequip: `this.changeAtks('player', {})`,
    },
}